CREATE DATABASE ARQUIVO; 
USE ARQUIVO;

-- CRIACAO DA TABELA USUARIO
CREATE TABLE USUARIO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY, 
EMAIL VARCHAR (100) UNIQUE NOT NULL, 
SENHA VARCHAR (12) NOT NULL,
PRIMEIRO_NOME VARCHAR (30) NOT NULL, 
SOBRENOME VARCHAR (50) NOT NULL, 
SEXO CHAR NOT NULL
);

-- CRIACAO DA TABELA POSTAGEM
CREATE TABLE POSTAGEM(
ID_POSTAGEM INT AUTO_INCREMENT PRIMARY KEY, 
TITULO VARCHAR (120) NOT NULL, 
CONTEUDO TEXT NOT NULL, 
AUTOR INT, 
FOREIGN KEY (AUTOR) REFERENCES USUARIO(ID_USUARIO)
);

-- CRIACAO DA TABELA COMENTARIO
CREATE TABLE COMENTARIO(
ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY, 
CORPO_COMENTARIO TEXT NOT NULL, 
POSTAGEM INT,
FOREIGN KEY (POSTAGEM) REFERENCES POSTAGEM (ID_POSTAGEM)
);
