CREATE DATABASE ARQUIVOS; 
USE ARQUIVOS;

-- CRIACAO DA TABELA NOMES
CREATE TABLE NOMES (
CODIGO SMALLINT PRIMARY KEY AUTO_INCREMENT, 
NOME VARCHAR (20) NOT NULL
);

-- INSERINDO VALORES NA TABELA 
INSERT INTO NOMES (NOME) VALUES ('RENATA');
INSERT INTO NOMES (NOME) VALUES ('JORGE');
INSERT INTO NOMES (NOME) VALUES ('JOAO');
INSERT INTO NOMES (NOME) VALUES ('FABIO');


-- SELECIONANDO O VALOR MAXIMO DO CODIGO
SELECT MAX(CODIGO)
FROM NOMES;

-- ALTERANDO O PRÓXIMO VALOR NO CAMPO DE AUTO-INCREMENTO
ALTER TABLE NOMES 
AUTO_INCREMENT = 90;
