CREATE DATABASE VENDAS; 
USE VENDAS;

-- CRIANDO A TABELA DADOS_PRODUTO
CREATE TABLE DADOS_PRODUTO (
CODIGO_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME_PRODUTO VARCHAR (50) NOT NULL,
VALOR DECIMAL (6,2) NOT NULL
);


-- CRIAÇAO DA TABELA CLIENTES
CREATE TABLE CLIENTES(
CODIGO_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME_CLIENTE VARCHAR (50) NOT NULL, 
DATA_NASCIMENTO DATETIME, 
SEXO VARCHAR (1) NOT NULL, 
ENDERECO VARCHAR (50),
CIDADE VARCHAR (50),
ESTADO VARCHAR (30),
TELEFONE_01 VARCHAR (15), 
TELEFONE_02 VARCHAR (15)
);

-- CRIAÇAO DA TABELA VENDAS
CREATE TABLE VENDAS(
CODIGO_VENDA INT PRIMARY KEY AUTO_INCREMENT,
CODIGO_CLIENTE INT NOT NULL REFERENCES CLIENTES (CODIGO_CLIENTE),
DATA_VENDA DATE NOT NULL
);

-- CRIAÇAO DA TABELA PRODUTO_VENDA
CREATE TABLE PRODUTO_VENDA(
CODIGO_PRODUTO_VENDA INT PRIMARY KEY AUTO_INCREMENT,
CODIGO_VENDA INT NOT NULL REFERENCES VENDA (CODIGO_VENDA),
CODIGO_PRODUTO INT NOT NULL REFERENCES DADOS_PRODUTO (CODIGO_PRODUTO),
QUANTIDADE_PRODUTO INT NOT NULL
);

-- FOREIGN KEY
-- CONSTRAINT
ALTER TABLE VENDAS
ADD CONSTRAINT FK_PRODUTO_VENDAS
FOREIGN KEY (CODIGO_PRODUTO) REFERENCES DADOS_PRODUTO (CODIGO_PRODUTO)

-- INSERINDO CONTEUDO NA TABELA DADOS_PRODUTO
INSERT INTO DADOS_PRODUTO (CODIGO_PRODUTO, NOME, VALOR)
VALUES (123,'SUCO DE LARANJA', 4.5),
	   (124, 'SUCO DE MANGA', 1.5),
       (125, 'SUCO DE ABACAXI', 5);
       
-- REMOVENDO A TABELA VENDAS
DROP TABLE VENDAS

-- CRIANDO NOVO CLIENTE
INSERT INTO CLIENTES (CODIGO_CLIENTE, NOME, DATA_NASCIMENTO, SEXO, ENDERECO, CIDADE, ESTADO,
TELEFONE_01, TELEFONE_02)
VALUES (015391, 'PAULO SILVA', '1987-04-29', 'M', 'RUA SANTOS 345', 'SAO PAULO', 'SAO PAULO',
'11 99345-5678', '11 2345-4567')


-- INSERINDO A VENDA
INSERT INTO VENDAS (CODIGO_VENDA, CODIGO_CLIENTE, DATA_VENDA)
VALUES (1235, 15391, CURRENT_DATE());

-- INSERINDO AS VENDAS
INSERT INTO PRODUTO_VENDA (CODIGO_PRODUTO_VENDA, CODIGO_VENDA, CODIGO_PRODUTO, QUANTIDADE_PRODUTO)
VALUES (1, 2, 123, 40),
	   (2, 3, 124, 33),
       (4, 5, 125, 20);
       
-- SELEÇAO DOS DADOS COM VALORES
SELECT TAB_VEND.CODIGO_VENDA, TAB_CL.NOME_CLIENTE, PROD.NOME, PROD_VEND.QUANTIDADE_PRODUTO, PROD.VALOR
FROM DADOS_PRODUTO PROD INNER JOIN PRODUTO_VENDA PROD_VEND ON PROD.CODIGO_PRODUTO = PROD_VEND.CODIGO_PRODUTO
INNER JOIN VENDAS TAB_VEND ON PROD_VEND.CODIGO_VENDA = TAB_VEND.CODIGO_VENDA
INNER JOIN CLIENTES TAB_CL ON TAB_VEND.CODIGO_CLIENTE = TAB_CL.CODIGO_CLIENTE


